const product = {
    ID: uuid.UUID,
    Name: string ,
    Stock: int,
    weight: float64,
    Price: float64,
    Description: string,
    ImageURL: string,
    CategoryID: uint,
    CategoryName: string,
    HasVariant: bool,
    ColorID: uint,
    ColorName: string,
    SizeID: uint,
    SizeName: string,
};
